name: Python Workflow

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pymongo
        pip install pandas
        pip install streamlit
        pip install plotly

    - name: Run Python script
      env:
        URI: ${{ secrets.URI }}
      run: |
        python -c "import os; os.environ('URI') = '${URI}'; print(os.environ('URI'))"
        python streamlit-mongo.py
